elevage_accueil:
    pattern:  /
    defaults: { _controller: PatrickElevageBundle:Default:index }

elevage_ajouter:
    pattern:  /admin/ajout
    defaults: { _controller: PatrickElevageBundle:Chiens:edit }

elevage_modifier:
    pattern:  /admin/modifier/{id}
    defaults: { _controller: PatrickElevageBundle:Chiens:edit }

elevage_concour_ajouter:
    pattern:  /admin/ajout/concour
    defaults: { _controller: PatrickElevageBundle:Concours:edit }

elevage_concour_modifier:
    pattern:  /admin/modifier/concour/{id}
    defaults: { _controller: PatrickElevageBundle:Concours:edit }

elevage_concour_chiens:
    pattern:  /concour/race/{race}
    defaults: { _controller: PatrickElevageBundle:Concours:show }

elevage_chiens:
    pattern:  /chien/race/{race}/chiot/{chiot}
    defaults: { _controller: PatrickElevageBundle:Chiens:show }

elevage_contact:
    pattern:  /contact
    defaults: { _controller: PatrickElevageBundle:Default:contact }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password