elevage_accueil:
    pattern:  /
    defaults: { _controller: PatrickElevageBundle:Default:index }

elevage_chiens:
    pattern:  /chien/race/{race}/chiot/{chiot}
    defaults: { _controller: PatrickElevageBundle:Chiens:show }

elevage_contact:
    pattern:  /contact
    defaults: { _controller: PatrickElevageBundle:Default:contact }

elevage_ajouter:
    pattern:  /admin/ajout
    defaults: { _controller: PatrickElevageBundle:Chiens:edit }

elevage_modifier:
    pattern:  /admin/modifier/{id}
    defaults: { _controller: PatrickElevageBundle:Chiens:edit }

elevage_supprimer:
    pattern:  /admin/supprimer/{id}
    defaults: { _controller: PatrickElevageBundle:Chiens:supprimer }

elevage_ajouter_presentation:
    pattern:  /admin/ajout/presentation
    defaults: { _controller: PatrickElevageBundle:Presentation:edit }

elevage_modifier_presentation:
    pattern:  /admin/ajout/presentation/{id}
    defaults: { _controller: PatrickElevageBundle:Presentation:edit }

elevage_concour_chiens:
    pattern:  /concours/race/{race}
    defaults: { _controller: PatrickElevageBundle:Concours:show }

elevage_concour_ajouter:
    pattern:  /admin/ajout/concours
    defaults: { _controller: PatrickElevageBundle:Concours:edit }

elevage_concour_modifier:
    pattern:  /admin/modifier/concours/{id}
    defaults: { _controller: PatrickElevageBundle:Concours:edit }

elevage_concour_supprimer:
    pattern:  /admin/supprimer/concours/{id}
    defaults: { _controller: PatrickElevageBundle:Concours:supprimer }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password